apiVersion: v1
kind: Secret
metadata:
  name: teste-secret
  namespace: apresentacao
  annotations:
    avp.kubernetes.io/path: prod/secret
stringData:
  #sample-secret: <string-connection>
  sample-secret-again: <path:prod/secret#string-connection#AWSCURRENT>
  sample-secret-old: <path:prod/secret#string-connection#AWSPREVIOUS>
#type: Opaque
