apiVersion: v1
kind: Secret
metadata:
  name: teste-secret
  namespace: apresentacao
  annotations:
    avp.kubernetes.io/path: prod/secret
type: Opaque
stringData:
  string-connection: <string-connection>
