---
apiVersion: external-secrets.io/v1beta1   ######### Não alterar ##### #####
kind: ExternalSecret                      ######### Não alterar ##### #####
metadata:                                 ######### Não alterar ##### #####
  name: aplicacao-teste-topan             # Nome da secret a ser criada no Kubernetes #
  namespace: cloudops                     # Namespace da aplicação #
spec:
  refreshInterval: "120s"                 ##### Não alterar, vai ser monitorado #####
  secretStoreRef:
    name: cluster-secret-store            ##### Não alterar #####
    kind: ClusterSecretStore              ##### Não alterar #####
  target:
    name: aplicacao-teste-topan           # Nome da secret a ser criada no Kubernetes #
    creationPolicy: Owner                 ##### Não alterar #####
  dataFrom:
  - extract:
      key: teste-lua                      # nome da secret cadastrada na AWS #
