apiVersion: v1
kind: Secret
metadata:
  name: teste-secret
  namespace: apresentacao
  annotations:
    avp.kubernetes.io/path: prod/secret
type: Opaque
stringData:
  sample-secret: <string-connection>
  sample-secret-again: <path:prod/secret#string-connection#AWSCURRENT>
  sample-secret-old: <path:prod/secret#string-connection#AWSPREVIOUS>
  sample-secret1: <string-teste>
  sample-secret-again1: <path:prod/secret#string-teste#AWSCURRENT>
  sample-secret-old1: <path:prod/secret#string-teste#AWSPREVIOUS>
