apiVersion: v1
kind: Secret
metadata:
  name: teste-secret
  namespace: apresentacao
  annotations:
    avp.kubernetes.io/path: prod/secret
type: Opaque
stringData:
  #sample-secret: <string-connection>
  #sample-secret-again: <path:prod/secret#string-connection#AWSCURRENT>
  #sample-secret-old: <path:prod/secret#string-connection#AWSPREVIOUS>
  sample-secrets: <string-teste>
  sample-secret-agains: <path:prod/secret#string-teste#AWSCURRENT>
  sample-secret-olds: <path:prod/secret#string-teste#AWSPREVIOUS>
